# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Get the fast C bindings:
#   gem install mysql
#   (on OS X: gem install mysql -- --include=/usr/local/lib)
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

<% case @database_type -%>
<% when "mysql" -%>
production:
  adapter: mysql2
  database: <%= @database_name %>
  host: <%= @database_host %>
  username: <%= @database_user %>
  password: <%= @database_password %>
  encoding: utf8

development:
  adapter: mysql2
  database: <%= @database_name %>
  host: <%= @database_host %>
  username: <%= @database_user %>
  password: <%= @database_password %>
  encoding: utf8

<% when "sqlite" -%>
production:
  adapter: sqlite3
  database: db/production.db
<% end -%>
